// Generated by CoffeeScript 2.1.1
var Vinyl, ar, assert, fs;

({assert} = require('chai'));

Vinyl = require('vinyl');

fs = require('fs');

ar = require('./');

describe('ar', function() {
  return it('extracts ar archive', function(done) {
    var buff, file, pipe, realFile;
    buff = fs.readFileSync('fixtures/hello.a');
    realFile = fs.readFileSync('fixtures/hello.txt');
    file = new Vinyl({
      name: 'hello.a',
      contents: buff
    });
    pipe = ar();
    pipe.write(file);
    return pipe.once('data', function(data) {
      if ((Buffer.compare(realFile, data.contents)) === 0) {
        return done();
      } else {
        return done(new Error('Extracted files are different!'));
      }
    });
  });
});
